export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function SingleCatItemsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen bg-gray-100">
      {children}
    </div>
  );
}
